# Generated by Django 4.1 on 2024-10-05 19:37

import cinema.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(null=True, upload_to=cinema.utils.get_image_path),
        ),
    ]
